version: '3'

networks:
  aurum_net:
    driver: bridge

services:
  user_register:
    depends_on:
      - database_service
    networks:
      aurum_net:
        aliases:
          - user_register
    ports:
      - 8000:8000
    build:
      context: ../user_register
      dockerfile: Dockerfile


  database_service:
    networks:
      aurum_net:
        aliases:
          - database_service
    build:
      context: ../database_service
      dockerfile: Dockerfile
