name: 'Integrate user register and its backend'
description: "install and basic test of user register with backend"
runs:
  using: composite
  steps:
    - run: echo user register and backend database_service integration test
      shell: bash
    - uses: actions/checkout@v2
      with:
        repository: benclifford/user_register
        ref: integration-testing
        path: user_register
    - uses: actions/checkout@v2
      with:
        repository: TheDataStation/database_service
        ref: main
        path: database_service
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install requirements.txt from both components together
      shell: bash
      run: |
        pip install -r user_register/requirements.txt -r database_service/requirements.txt


