name: CI_datastation_integration

on: push

jobs:
  integration-test-user-register:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/integ-user-register
        with:
          integration_repository: ${{ github.repository }}
          integration_commit: ${{ github.ref }}


  integration-test-aurum:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/integ-aurum
        with:
          integration_repository: ${{ github.repository }}
          integration_commit: ${{ github.ref }}
